[package]
name = "libremarkable"
version = "0.4.3"
authors = ["Can Selcik <contact@cselcik.com>"]
repository = "https://github.com/canselcik/libremarkable"
license = "MIT"
description = "The only publicly available Framework for developing applications for the Remarkable Paper Tablet w/ Low Latency Partial Refresh Support"
readme = "README.md"
exclude = [ "reference-material/*", "legacy-c-impl/*", "private/*" ]
edition = "2018"

[dependencies]
log = "0.4.8"
env_logger = "0.7.1"
lazy_static = "1.4.0"
atomic = "0.5.0"
cgmath = "0.17.0"
libc = "0.2.69"

# input
evdev = "0.10.2"
epoll = "4.1.0"
fxhash = "0.2.1"

# framebuffer
rusttype = { version = "0.8.2", optional = true }
mmap = { version = "0.1.1", optional = true }
image = { version = "0.21.3", optional = true }
ioctl-gen = { version = "0.1.1", optional = true }
line_drawing = { version = "0.8.0", optional = true }
zstd = { version = "0.5.1", optional = true }

# appctx
aabb-quadtree = { version = "0.1.0", optional = true }
hlua = { version = "0.4.1", optional = true }

# runtime benchmarking
stopwatch = { version = "0.0.7", optional = true }


[features]
default = ["framebuffer", "appctx"]

framebuffer = ["rusttype", "mmap", "image", "ioctl-gen", "line_drawing", "zstd"]
appctx = ["aabb-quadtree", "hlua"]

enable-runtime-benchmarking = ["stopwatch"]

[profile.release]
debug = true
lto = true

[[example]]
name = "spy"
path = "examples/spy.rs"
crate-type = ["dylib"]

[[example]]
name = "demo"
path = "examples/demo.rs"
crate-type = ["bin"]

[[example]]
name = "live"
path = "examples/live.rs"
crate-type = ["bin"]

[dev-dependencies]
# For spy
redhook = "2.0.0"
libc = "0.2.69"
lazy_static = "1.4.0"
# For demo
chrono = "0.4.11"
# For live
tiny_http = "0.6.2"
